server:
  error:
    include-stacktrace: ON_PARAM
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/note?createDatabaseIfNotExist=true
    username: root
    password: 123456
    #url: jdbc:mysql://200.128.9.179:3306/note?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    
    #url: jdbc:mysql://10.28.0.35:3306/note?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    #username: remoto
    #password: remoto
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true